import enum

class UserRole(str, enum.Enum):
    EMPLOYEE = "EMPLOYEE"
    IT_SUPPORT = "IT_SUPPORT"
    IT_MANAGER = "IT_MANAGER"
    ADMIN = "ADMIN"

class Priority(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class RequestStatus(str, enum.Enum):
    NEW = "NEW"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    ON_HOLD = "ON_HOLD"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"

class ActionType(str, enum.Enum):
    CREATED = "CREATED"
    ASSIGNED = "ASSIGNED"
    REASSIGNED = "REASSIGNED"
    STATUS_CHANGED = "STATUS_CHANGED"
    PRIORITY_CHANGED = "PRIORITY_CHANGED"
    CATEGORY_CHANGED = "CATEGORY_CHANGED"
    COMMENT_ADDED = "COMMENT_ADDED"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
    REOPENED = "REOPENED"
    UPDATED = "UPDATED"

class SLAStatus(str, enum.Enum):
    WITHIN_SLA = "WITHIN_SLA"
    APPROACHING_BREACH = "APPROACHING_BREACH"
    SLA_BREACHED = "SLA_BREACHED"
    RESOLVED_WITHIN_SLA = "RESOLVED_WITHIN_SLA"
    RESOLVED_BREACHED = "RESOLVED_BREACHED"
